/**从文件提取的预定义的ItemActionID 列表*/
export const ExtractDefineItemActionIDList = [
    "repair_fabric"               , // 修理棉/皮/羊毛/芳纶/毛皮制品
    "repair_metal"                , // 修理金属/塑料/凯夫拉制品
    "sew_advanced"                , // 修改衣物
    "firestarter"                 , // 快速生火
    "PICK_LOCK"                   , // 撬锁
    "deploy_furn"                 , // 放置物品
    "deploy_appliance"            , // 放置物品
    "CROWBAR_WEAK"                , // 撬开板条箱/钉子
    "CROWBAR"                     , // 撬开
    "MAKEMOUND"                   , // 翻耕土壤
    "DIG_CHANNEL"                 , // 挖排水沟
    "PICKAXE"                     , // 挖掘岩石
    "PACK_CBM"                    , // CBM 装袋
    "GEIGER"                      , // 使用盖格计数器
    "HACKSAW"                     , // 切割金属
    "BOLTCUTTERS"                 , // 切断螺栓/铁丝
    "HOTPLATE"                    , // 加热食物（使用此工具热源）
    "HOTPLATE_ATOMIC"             , // 加热食物（使用此工具热源）
    "TOOLMOD_ATTACH"              , // 安装工具模组
    "GUNMOD_ATTACH"               , // 安装枪械模组
    "GUN_REPAIR"                  , // 修理枪械
    "DIRECTIONAL_HOLOGRAM"        , // 产生全息投影
    "ROBOTCONTROL"                , // 黑掉机器人
    "METH"                        , // 吸食
    "TAZER"                       , // 电击
    "ANTICONVULSANT"              , // 服用抗痉挛药
    "LUMBER"                      , // 加工原木
    "REMOVE_ALL_MODS"             , // 拆卸模组
    "salvage"                     , // 切割物品
    "inscribe"                    , // 铭刻物品
    "fireweapon_off"              , // 开启
    "fireweapon_on"               , // 关闭
    "CHANGE_EYES"                 , // 改变眼睛颜色
    "CHANGE_SKIN"                 , // 改变肤色
    "transform"                   , // 开启
    "message"                     , // 激活
    "unpack"                      , // 拆包
    "learn_spell"                 , // 学习法术
    "cast_spell"                  , // 施放法术
    "holster"                     , // 使用枪套/刀鞘
    "attach_molle"                , // 安装口袋
    "detach_molle"                , // 取下口袋
    "saw_barrel"                  , // 锯短枪管
    "saw_stock"                   , // 锯短枪托
    "ACIDBOMB_ACT"                , // 激活
    "ADRENALINE_INJECTOR"         , // 注射
    "AFS_TRANSLOCATOR"            , // 建立浮标
    "ALCOHOL"                     , // 饮料
    "ALCOHOL_STRONG"              , // 饮料
    "ALCOHOL_WEAK"                , // 饮料
    "ANTIBIOTIC"                  , // 服用
    "ANTIFUNGAL"                  , // 服用
    "ANTIPARASITIC"               , // 服用
    "BELL"                        , // 摇铃
    "BLECH"                       , // 饮料
    "BLECH_BECAUSE_UNCLEAN"       , // 饮料
    "C4"                          , // 激活
    "CAMERA"                      , // 使用摄像头
    "CAN_GOO"                     , // 倒出
    "CAPTURE_MONSTER_ACT"         , // 捕捉/放置
    "CAPTURE_MONSTER_VEH"         , // 捕捉/放置
    "CHEW"                        , // 食用
    "CLEAR_RUBBLE"                , // 清理瓦砾
    "COIN_FLIP"                   , // 抛硬币
    "BINDER_ADD_RECIPE"           , // 复制配方
    "BINDER_MANAGE_RECIPE"        , // 删除配方
    "COKE"                        , // 吸食
    "DATURA"                      , // 食用
    "DIG"                         , // 挖坑
    "DIRECTIONAL_ANTENNA"         , // 搜寻信号
    "DOG_WHISTLE"                 , // 吹响
    "CALL_OF_TINDALOS"            , // 吹响
    "DOLLCHAT"                    , // 和其交谈
    "ECIG"                        , // ECIG
    "EHANDCUFFS"                  , // 脱下
    "EBOOKSAVE"                   , // 保存书籍
    "EMF_PASSIVE_ON"              , // 关闭
    "EXTINGUISHER"                , // 喷射
    "MACE"                        , // 喷射
    "EYEDROPS"                    , // 使用
    "FILL_PIT"                    , // 填坑/夯实地面
    "FIRECRACKER"                 , // 点燃
    "FIRECRACKER_PACK"            , // 点燃
    "FIRECRACKER_PACK_ACT"        , // 点燃
    "FISH_ROD"                    , // FISH_ROD
    "FISH_TRAP"                   , // 设置
    "FLUMED"                      , // 服用
    "FLUSLEEP"                    , // 服用
    "FLU_VACCINE"                 , // 注射
    "FOODPERSON"                  , // 激活
    "FUNGICIDE"                   , // 服用
    "GRANADE_ACT"                 , // 激活
    "GRENADE_INC_ACT"             , // 激活
    "detach_gunmods"              , // 拆卸模组
    "modify_gunmods"              , // 调整模组
    "HEATPACK"                    , // 使用
    "HEAT_FOOD"                   , // 加热食物（使用其他热源）
    "HEAT_LIQUID_ITEMS"           , // 加热液体
    "HEAT_SOLID_ITEMS"            , // 加热固体
    "HEAT_ALL_ITEMS"              , // 加热固体/液体
    "HONEYCOMB"                   , // 服用
    "INHALER"                     , // 吸入
    "JACKHAMMER"                  , // 钻孔
    "JET_INJECTOR"                , // 注射
    "MAGIC_8_BALL"                , // 询问
    "MEASURE_RESONANCE"           , // 共鸣测量器
    "CHANGE_OUTFIT"               , // 切换装束
    "PLAY_GAME"                   , // 演奏
    "MARLOSS"                     , // 服用
    "MARLOSS_GEL"                 , // 服用
    "MARLOSS_SEED"                , // 服用
    "MA_MANUAL"                   , // 阅读
    "MEDITATE"                    , // 冥想
    "MININUKE"                    , // 激活
    "MOLOTOV_LIT"                 , // 点燃
    "MOP"                         , // 清扫
    "MP3"                         , // 播放音乐
    "MP3_DEACTIVATE"              , // 关闭音乐
    "RPGDIE"                      , // 掷骰子
    "GASMASK_ACTIVATE"            , // 增压与吸力测试
    "DIVE_TANK_ACTIVATE"          , // 开启气阀
    "SOLARPACK"                   , // 展开
    "SOLARPACK_OFF"               , // 折叠
    "MULTICOOKER"                 , // 烹饪
    "MYCUS"                       , // 服用
    "NOISE_EMITTER_ON"            , // 关闭
    "OXYGEN_BOTTLE"               , // 吸入
    "OXYTORCH"                    , // 切割金属
    "PACK_ITEM"                   , // 打包物品
    "PETFOOD"                     , // 给动物喂食
    "PLANTBLECH"                  , // 服用
    "POISON"                      , // 服用
    "PORTABLE_GAME"               , // PORTABLE_GAME
    "FITNESS_CHECK"               , // 查看健康指标
    "deploy_tent"                 , // 搭建
    "PORTAL"                      , // 地点
    "POST_UP"                     , // 搭建
    "PROZAC"                      , // 服用
    "E_FILE_DEVICE"               , // 管理文件
    "VIEW_RECIPES"                , // 查看配方
    "VIEW_PHOTOS"                 , // 查看照片
    "PURIFY_SMART"                , // 注射
    "RADGLOVE"                    , // 测量辐射
    "RADIOCAR"                    , // ……
    "RADIOCARON"                  , // 关闭
    "RADIOCONTROL"                , // 控制遥控车
    "RADIO_MOD"                   , // 改造物品
    "RADIO_OFF"                   , // 开启
    "RADIO_ON"                    , // 扫描
    "REMOTEVEH"                   , // 控制载具
    "MANAGE_EXOSUIT"              , // 管理动力装甲模块
    "SEED"                        , // 服用
    "SEWAGE"                      , // 服用
    "SHOCKTONFA_OFF"              , // 开启
    "SHOCKTONFA_ON"               , // 关闭
    "SIPHON"                      , // 抽取
    "SMOKING"                     , // SMOKING
    "SPRAY_CAN"                   , // 涂鸦
    "STIMPACK"                    , // 注射
    "TELEPORT"                    , // 传送自己
    "THORAZINE"                   , // 服用
    "TOWEL"                       , // 擦干/清洁自己
    "UNFOLD_GENERIC"              , // 展开
    "UNPACK_ITEM"                 , // 拆包
    "BLOOD_DRAW"                  , // 采集血样
    "HAND_CRANK"                  , // 手摇充电
    "VIBE"                        , // 放松一下
    "VORTEX"                      , // 使用
    "WASH_SOFT_ITEMS"             , // 清洗软物
    "WASH_HARD_ITEMS"             , // 清洗硬物
    "WASH_ALL_ITEMS"              , // 清洗物品
    "WATER_PURIFIER"              , // 净水
    "WATER_TABLETS"               , // 净水
    "WEATHER_TOOL"                , // 测量天气信息
    "WEED_CAKE"                   , // 服用
    "XANAX"                       , // 服用
    "ammobelt"                    , // 装填
    "consume_drug"                , // 服用
    "delayed_transform"           , // 使用
    "explosion"                   , // 激活
    "heal"                        , // 疗伤
    "link_up"                     , // 接入/管理电网
    "manualnoise"                 , // 制造噪音
    "musical_instrument"          , // musical_instrument
    "place_monster"               , // 激活
    "place_npc"                   , // 激活
    "place_trap"                  , // 地点
    "reveal_map"                  , // 阅读
    "change_scent"                , // 掩盖体味
    "install_bionic"              , // 安装插件
    "CHOP_TREE"                   , // 砍倒树木
    "CHOP_LOGS"                   , // 树干劈成原木
    "BREAK_STICK"                 , // 折断木棍
    "WEAK_ANTIBIOTIC"             , // 服用
    "DISASSEMBLE"                 , // 获得内容物
    "STRONG_ANTIBIOTIC"           , // 服用
    "weigh_self"                  , // 称体重
    "CRAFT"                       , // 继续制造
    "effect_on_conditions"        , // 激活物品
    "SEXTANT"                     , // 观测太阳高度
    "LUX_METER"                   , // 测量照度
    "DBG_LUX_METER"               , // 测量照度
    "CALORIES_INTAKE_TRACKER"     , // 热量摄取记录
    "VOLTMETER"                   , // 测量电压
    "play_instrument"             , // 演奏乐器
    "sound"                       , // 发出声音
] as const;
/**从文件提取的预定义的ItemActionID */
export type ExtractDefineItemActionID = typeof ExtractDefineItemActionIDList[number];