/**从文件提取的预定义的MaterialID 列表*/
export const ExtractDefineMaterialIDList = [
    "undefined"                   , // 聚合树脂
    "thermo_resin"                , // 热塑树脂
    "epoxy"                       , // 环氧树脂
    "fiberglass"                  , // 玻纤层压板
    "carbonfiber"                 , // 碳纤维复合材料
    "pseudo_fuel"                 , // 虚拟燃料
    "battery"                     , // 电池
    "wind"                        , // 风速
    "sunlight"                    , // 阳光
    "animal"                      , // 畜力
    "muscle"                      , // 肌肉
    "metabolism"                  , // 代谢
    "alcohol"                     , // 酒精
    "paint"                       , // 颜料
    "isopropyl"                   , // 异丙基酒精
    "alien_liquid"                , // 非牛顿流体
    "alien_resin"                 , // 树脂
    "aluminum"                    , // 铝
    "bone"                        , // 骨头
    "brass"                       , // 黄铜
    "bronze"                      , // 青铜
    "alien_carapace"              , // 甲壳
    "fancy_bronze"                , // 帖撒罗尼迦青铜
    "budget_steel"                , // 粗钢
    "cardboard"                   , // 硬纸板
    "ceramic"                     , // 陶瓷
    "yrax_quartz"                 , // 石英
    "damaged_ceramic"             , // 复合陶瓷
    "hyperweave_off"              , // 惰性超织物
    "hyperweave_on"               , // 充能超织物
    "chitin"                      , // 硬化甲壳
    "acidchitin"                  , // 硅化甲壳
    "chitin_light"                , // 轻薄甲壳
    "sclerotin_light"             , // 轻薄骨质
    "sclerotin"                   , // 硬化骨质
    "clay"                        , // 黏土
    "porcelain"                   , // 陶瓷
    "copper"                      , // 铜
    "cotton"                      , // 棉
    "cotton_quilted"              , // 绗缝棉布
    "cotton_quilted_salted"       , // 盐硬化绗缝棉
    "denim"                       , // 牛仔布
    "canvas"                      , // 帆布
    "canvas_quilted"              , // 绗缝帆布
    "canvas_quilted_2"            , // 绗缝帆布
    "diamond"                     , // 钻石
    "gemstone"                    , // 宝石
    "egg"                         , // 蛋
    "flesh"                       , // 肉
    "drug_filler"                 , // 药品
    "gutskin"                     , // 肠衣
    "freshclay"                   , // 黏土（新鲜）
    "fruit"                       , // 水果
    "fur"                         , // 毛皮
    "faux_fur"                    , // 人造毛皮
    "lvl4ballisticglass"          , // 防弹玻璃
    "glass"                       , // 玻璃
    "crystal"                     , // 水晶
    "gold"                        , // 黄金
    "hflesh"                      , // 人肉
    "honey"                       , // 蜂蜜
    "sugar"                       , // 糖
    "hydrocarbons"                , // 碳氢化合物
    "diesel"                      , // 柴油
    "jp8"                         , // JP8
    "avgas"                       , // 航空燃油
    "biodiesel"                   , // 生物柴油
    "gasoline"                    , // 汽油
    "lamp_oil"                    , // 煤油
    "crude_lamp_oil"              , // 自制灯油
    "motor_oil"                   , // 机油
    "crude_oil"                   , // 原油
    "iflesh"                      , // 虫肉
    "iron"                        , // 铸铁
    "junk"                        , // 垃圾食品
    "bread"                       , // 面包
    "foodplace_foodstuff"         , // 美食广场美食™
    "kevlar"                      , // 凯夫拉
    "kevlar_layered"              , // 防弹凯夫拉
    "kevlar_rigid"                , // 硬凯夫拉
    "lead"                        , // 铅
    "leather"                     , // 皮革
    "leather_treated"             , // 防水皮革
    "leather_arthropod"           , // 上表皮层
    "lycra"                       , // 氨纶
    "milk"                        , // 乳制品
    "neoprene"                    , // 氯丁橡胶
    "nomex"                       , // 芳纶
    "null"                        , // 未知
    "oil"                         , // 油
    "beeswax"                     , // 蜂蜡
    "paraffin_wax"                , // 石蜡
    "paper"                       , // 纸
    "dry_plant"                   , // 植物纤维
    "plastic"                     , // 塑料
    "hard_plastic_transp"         , // 透明抗冲击塑料
    "composite_transp"            , // 透明防弹复合物
    "plastic_pad"                 , // 塑料衬垫
    "rdx"                         , // RDX炸药
    "tnt"                         , // 三硝基甲苯
    "powder"                      , // 粉末
    "powder_nonflam"              , // 粉末
    "salt"                        , // 盐
    "mercury"                     , // 汞
    "silver"                      , // 银
    "platinum"                    , // 铂金
    "rubber"                      , // 橡胶
    "butyl_rubber"                , // 可塑橡胶
    "vinyl"                       , // 乙烯基塑料
    "slime"                       , // 变形怪
    "lc_steel"                    , // 低碳钢
    "mc_steel"                    , // 中碳钢
    "hc_steel"                    , // 高碳钢
    "ch_steel"                    , // 表面硬化碳钢
    "qt_steel"                    , // 回火碳钢
    "exodii_ceramic"              , // 流亡族陶瓷
    "budget_steel_chain"          , // 粗钢
    "lc_steel_chain"              , // 低碳钢
    "mc_steel_chain"              , // 中碳钢
    "hc_steel_chain"              , // 高碳钢
    "ch_steel_chain"              , // 表面硬化钢链
    "qt_steel_chain"              , // 回火碳钢
    "steel"                       , // 钢
    "plut_cell"                   , // 充能纳米复合材料（钚电池）
    "plutonium"                   , // 钚
    "uran_cell"                   , // 铀电池
    "hydrogen_cell"               , // 固态氢
    "gas"                         , // 天然气
    "nitrogen"                    , // 氮气
    "oxygen"                      , // 氧气
    "hydrogen"                    , // 氢气
    "stone"                       , // 石
    "rhodonite"                   , // 蔷薇辉石
    "zincite"                     , // 红锌矿
    "slaked_lime"                 , // 熟石灰
    "quicklime"                   , // 生石灰
    "cement"                      , // 水泥
    "monolith"                    , // 黑石
    "ballistic_shield"            , // 防弹屏障
    "monolith_heavy"              , // 黑石
    "anomaly"                     , // 异常材质
    "superalloy"                  , // 超合金
    "carbide"                     , // 层叠碳化物
    "nylon"                       , // 化纤织物
    "nylon_2"                     , // 化纤织物
    "nylon_quilted"               , // 绗缝尼龙
    "nylon_quilted_2"             , // 绗缝尼龙
    "carpet_pilling"              , // 地毯起球
    "unobtanium"                  , // 奇特金属
    "tin"                         , // 锡
    "veggy"                       , // 植物质
    "tomato"                      , // 番茄
    "bean"                        , // 豆类
    "garlic"                      , // 大蒜
    "nut"                         , // 坚果
    "mushroom"                    , // 蘑菇
    "mold"                        , // 霉菌
    "yeast"                       , // 酵母
    "water"                       , // 水
    "blood"                       , // 血液
    "hblood"                      , // 人类血液
    "acetone"                     , // 丙酮
    "acid"                        , // 酸液
    "wheat"                       , // 小麦
    "wood"                        , // 木头
    "charcoal"                    , // 木炭
    "coal"                        , // 煤炭
    "wool"                        , // 羊毛
    "wool_quilted"                , // 绗缝羊毛
    "wool_quilted_2"              , // 绗缝羊毛
    "feces"                       , // 粪便
    "dried_vegetable"             , // 干蔬菜
    "cured_meat"                  , // 腌肉
    "processed_food"              , // 加工食品
    "cheese"                      , // 奶酪
    "ice_cream"                   , // 冰淇淋
    "soil"                        , // 泥土
    "sand"                        , // 沙
    "zinc"                        , // 锌
    "propane"                     , // 丙烷
    "slag"                        , // 熔渣
    "ammonia_hydroxide"           , // 氢氧化氨
    "ammonia_liquid"              , // 液氨
    "turpentine"                  , // 松节油
    "nanotubes"                   , // 碳晶格
    "asbestos"                    , // 石棉
    "mut_feather"                 , // 变异羽毛
    "mut_fur"                     , // 变异毛皮
    "mut_wood"                    , // 变异木头
    "mut_bone"                    , // 变异骨头
    "mut_scales"                  , // 变异鳞片
    "mi-go_flesh"                 , // 米戈肉
    "mi-go_blood"                 , // 米戈体液
    "mi-go_bone"                  , // 米戈骨骼
] as const;
/**从文件提取的预定义的MaterialID */
export type ExtractDefineMaterialID = typeof ExtractDefineMaterialIDList[number];